# Generated by Django 4.0.6 on 2022-07-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='roomID',
        ),
    ]
